package com.likeme.category.model;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbggenerated
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_description
     *
     * @mbggenerated
     */
    private String categoryDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_img
     *
     * @mbggenerated
     */
    private String categoryImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated
     */
    public Category(String id, String categoryName, String categoryDescription, String categoryImg) {
        this.id = id;
        this.categoryName = categoryName;
        this.categoryDescription = categoryDescription;
        this.categoryImg = categoryImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated
     */
    public Category() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_name
     *
     * @return the value of category.category_name
     *
     * @mbggenerated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_name
     *
     * @param categoryName the value for category.category_name
     *
     * @mbggenerated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_description
     *
     * @return the value of category.category_description
     *
     * @mbggenerated
     */
    public String getCategoryDescription() {
        return categoryDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_description
     *
     * @param categoryDescription the value for category.category_description
     *
     * @mbggenerated
     */
    public void setCategoryDescription(String categoryDescription) {
        this.categoryDescription = categoryDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_img
     *
     * @return the value of category.category_img
     *
     * @mbggenerated
     */
    public String getCategoryImg() {
        return categoryImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_img
     *
     * @param categoryImg the value for category.category_img
     *
     * @mbggenerated
     */
    public void setCategoryImg(String categoryImg) {
        this.categoryImg = categoryImg;
    }
}